//! Per-font glyph ink-coverage tables (PLAN §3.4, M5 item B).
//!
//! Terminals cannot be queried for their font, so the engine ships coverage
//! tables for common monospace fonts (committed under `crates/slpy-core/fonts/`, generated by
//! `sleepy-factory font-table`) plus a conservative default, and
//! `--font-table NAME|PATH` lets the user assert which font their terminal
//! runs. A [`FontTable`] carries two things:
//!
//! - **coverage** per palette glyph (fraction of the 64×128 cell inked) —
//!   what `slpy-eval`'s rasterizer scores SSIM through;
//! - the font's **repertoire** (which palette glyphs exist at all) — what
//!   [`FontTable::veto_tier`] uses to downgrade a glyph tier the font cannot
//!   render (§3.4: "the table records the font's repertoire so palette
//!   selection can veto").
//!
//! The on-disk format is the generator's deterministic TOML (see
//! `crates/slpy-core/fonts/README.md`). The parser here is a hand-rolled reader of exactly
//! that emitter subset — line-based `key = value`, one-line `missing`
//! array, `[[glyphs]]` tables — keeping slpy-core at zero dependencies
//! (PLAN §8). Unknown keys are ignored (forward-compatible); structural
//! errors are `Err`, not panics (tables are user input via `--font-table
//! PATH`).

use crate::palette::{GlyphTier, tier_glyphs};

/// A parsed font coverage table. See the module docs.
#[derive(Clone, Debug)]
pub struct FontTable {
    name: String,
    /// Sorted by char for binary search: `(glyph, coverage 0..=1)`.
    entries: Vec<(char, f32)>,
    /// Glyphs listed by the table but absent from the font (`coverage` is 0
    /// for these; they are NOT part of the repertoire).
    missing: Vec<char>,
}

/// Names of the committed built-in tables (`crates/slpy-core/fonts/*.toml`), resolvable via
/// [`FontTable::builtin`]: the four common monospace fonts of PLAN §3.4 plus
/// the conservative (ASCII-repertoire) default.
pub const BUILTIN_FONT_TABLES: &[&str] = &[
    "conservative",
    "dejavu-sans-mono",
    "liberation-mono",
    "ubuntu-mono",
    "noto-sans-mono",
];

impl FontTable {
    /// Parse a table in the `sleepy-factory font-table` output format.
    ///
    /// # Errors
    /// A human-readable message on structural problems: missing `name`, no
    /// glyphs, duplicate glyphs, coverage outside `0.0..=1.0`, malformed
    /// strings/floats.
    pub fn parse(text: &str) -> Result<FontTable, String> {
        let mut name: Option<String> = None;
        let mut missing: Vec<char> = Vec::new();
        let mut entries: Vec<(char, f32)> = Vec::new();
        // Per-[[glyphs]] state: Some(pending char) once `ch =` was seen.
        let mut in_glyph = false;
        let mut cur_ch: Option<char> = None;
        let mut cur_cov: Option<f32> = None;

        let mut flush = |ch: Option<char>, cov: Option<f32>| -> Result<(), String> {
            match (ch, cov) {
                (None, None) => Ok(()), // empty [[glyphs]] header just opened
                (Some(c), Some(v)) => {
                    if !(0.0..=1.0).contains(&v) {
                        return Err(format!("coverage for {c:?} out of range: {v}"));
                    }
                    entries.push((c, v));
                    Ok(())
                }
                (Some(c), None) => Err(format!("glyph {c:?} has no coverage value")),
                (None, Some(_)) => Err("coverage value without a ch".into()),
            }
        };

        for (ln, raw) in text.lines().enumerate() {
            let line = raw.trim();
            let err = |m: String| format!("font table line {}: {m}", ln + 1);
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line == "[[glyphs]]" {
                flush(cur_ch.take(), cur_cov.take()).map_err(&err)?;
                in_glyph = true;
                continue;
            }
            if line.starts_with('[') {
                // Some other table — tolerate (forward compat), leave glyph scope.
                flush(cur_ch.take(), cur_cov.take()).map_err(&err)?;
                in_glyph = false;
                continue;
            }
            let Some((key, val)) = line.split_once('=') else {
                return Err(err(format!("expected `key = value`, got {line:?}")));
            };
            let (key, val) = (key.trim(), val.trim());
            if in_glyph {
                match key {
                    "ch" => {
                        if cur_ch.is_some() || cur_cov.is_some() {
                            // `ch` twice without [[glyphs]] separator.
                            flush(cur_ch.take(), cur_cov.take()).map_err(&err)?;
                        }
                        cur_ch = Some(parse_char(val).map_err(&err)?);
                    }
                    "coverage" => {
                        cur_cov = Some(
                            val.parse::<f32>()
                                .map_err(|e| err(format!("bad coverage {val:?}: {e}")))?,
                        );
                    }
                    _ => {} // cp, lstar, future fields: ignored
                }
            } else {
                match key {
                    "name" => name = Some(parse_string(val).map_err(&err)?),
                    "missing" => missing = parse_char_array(val).map_err(&err)?,
                    _ => {} // schema, source, cell, px_per_em, ...: ignored
                }
            }
        }
        flush(cur_ch.take(), cur_cov.take())?;

        let name = name.ok_or("font table has no `name`")?;
        if entries.is_empty() {
            return Err(format!("font table {name:?} has no [[glyphs]] entries"));
        }
        entries.sort_unstable_by_key(|&(c, _)| c);
        for w in entries.windows(2) {
            if w[0].0 == w[1].0 {
                return Err(format!("duplicate glyph {:?} in font table {name:?}", w[0].0));
            }
        }
        missing.sort_unstable();
        missing.dedup();
        Ok(FontTable { name, entries, missing })
    }

    /// A committed built-in table by name (see [`BUILTIN_FONT_TABLES`]).
    pub fn builtin(name: &str) -> Option<&'static FontTable> {
        builtin_table(name)
    }

    /// Table name (the generator's `--name`, e.g. `"dejavu-sans-mono"`).
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Ink coverage for `ch` (0 for listed-but-missing glyphs), or `None`
    /// when the table does not list `ch` at all.
    pub fn coverage(&self, ch: char) -> Option<f32> {
        self.entries.binary_search_by_key(&ch, |&(c, _)| c).ok().map(|i| self.entries[i].1)
    }

    /// Is `ch` in the font's repertoire (listed AND not in `missing`)?
    pub fn has_glyph(&self, ch: char) -> bool {
        self.coverage(ch).is_some() && self.missing.binary_search(&ch).is_err()
    }

    /// Glyphs the table records as absent from the font.
    pub fn missing(&self) -> &[char] {
        &self.missing
    }

    /// `(glyph, coverage)` entries, sorted by glyph.
    pub fn entries(&self) -> &[(char, f32)] {
        &self.entries
    }

    /// The §3.4 repertoire veto: the highest tier at or below `want` whose
    /// full glyph surface ([`tier_glyphs`]) the font covers. Tiers only ever
    /// degrade Braille → UnicodeBlocks → Ascii; Ascii is the floor (never
    /// vetoed — every terminal font renders ASCII, and there is nothing
    /// below it to fall to).
    pub fn veto_tier(&self, want: GlyphTier) -> GlyphTier {
        let covered = |tier: GlyphTier| tier_glyphs(tier).iter().all(|&ch| self.has_glyph(ch));
        match want {
            GlyphTier::BrailleVerified if covered(GlyphTier::BrailleVerified) => want,
            GlyphTier::Ascii => GlyphTier::Ascii,
            _ if covered(GlyphTier::UnicodeBlocks) => GlyphTier::UnicodeBlocks,
            _ => GlyphTier::Ascii,
        }
    }
}

/// Parse a TOML basic string `"..."` with the emitter's escape set plus the
/// common TOML escapes (`\" \\ \n \t \r \uXXXX \UXXXXXXXX`).
fn parse_string(val: &str) -> Result<String, String> {
    let inner = val
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .ok_or_else(|| format!("expected a quoted string, got {val:?}"))?;
    let mut out = String::new();
    let mut it = inner.chars();
    while let Some(c) = it.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match it.next() {
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some(u @ ('u' | 'U')) => {
                let n = if u == 'u' { 4 } else { 8 };
                let hex: String = it.by_ref().take(n).collect();
                if hex.len() != n {
                    return Err(format!("truncated \\{u} escape in {val:?}"));
                }
                let cp = u32::from_str_radix(&hex, 16)
                    .map_err(|e| format!("bad \\{u} escape in {val:?}: {e}"))?;
                out.push(
                    char::from_u32(cp).ok_or_else(|| format!("invalid scalar U+{cp:04X}"))?,
                );
            }
            other => return Err(format!("unsupported escape \\{other:?} in {val:?}")),
        }
    }
    Ok(out)
}

/// A quoted string that must be exactly one char (the `ch` key).
fn parse_char(val: &str) -> Result<char, String> {
    let s = parse_string(val)?;
    let mut it = s.chars();
    match (it.next(), it.next()) {
        (Some(c), None) => Ok(c),
        _ => Err(format!("expected a single glyph, got {s:?}")),
    }
}

/// One-line array of quoted single-char strings: `["╱", "╲"]`.
fn parse_char_array(val: &str) -> Result<Vec<char>, String> {
    let inner = val
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .ok_or_else(|| format!("expected a one-line array, got {val:?}"))?;
    let inner = inner.trim();
    if inner.is_empty() {
        return Ok(Vec::new());
    }
    inner.split(',').map(|item| parse_char(item.trim())).collect()
}

/// Committed built-in tables (`crates/slpy-core/fonts/*.toml` — packaged with the crate; the same
/// files `crates/slpy-core/fonts/README.md` documents). Parsed once, on first use; a parse
/// failure here is a build-artifact defect and panics with the table name.
fn builtin_table(name: &str) -> Option<&'static FontTable> {
    use std::sync::LazyLock;
    macro_rules! builtin {
        ($static_name:ident, $file:literal) => {{
            static $static_name: LazyLock<FontTable> = LazyLock::new(|| {
                FontTable::parse(include_str!(concat!("../fonts/", $file)))
                    .unwrap_or_else(|e| panic!("builtin font table {}: {e}", $file))
            });
            Some(&*$static_name)
        }};
    }
    match name {
        "conservative" => builtin!(CONSERVATIVE, "conservative.toml"),
        "dejavu-sans-mono" => builtin!(DEJAVU, "dejavu-sans-mono.toml"),
        "liberation-mono" => builtin!(LIBERATION, "liberation-mono.toml"),
        "ubuntu-mono" => builtin!(UBUNTU, "ubuntu-mono.toml"),
        "noto-sans-mono" => builtin!(NOTO, "noto-sans-mono.toml"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::palette::all_palette_glyphs;

    const SAMPLE: &str = r#"
# comment
schema = 1
name = "sample"
source = "x.ttf"
missing = ["╱", "╲"]

[[glyphs]]
ch = " "
cp = 0x0020
coverage = 0.000000
lstar = 0.000

[[glyphs]]
ch = "\""
coverage = 0.063800

[[glyphs]]
ch = "╱"
coverage = 0.000000

[[glyphs]]
ch = "╲"
coverage = 0.000000

[[glyphs]]
ch = "█"
coverage = 0.960000
"#;

    #[test]
    fn parses_the_emitter_format() {
        let t = FontTable::parse(SAMPLE).unwrap();
        assert_eq!(t.name(), "sample");
        assert_eq!(t.entries().len(), 5);
        assert_eq!(t.coverage('"'), Some(0.0638));
        assert_eq!(t.coverage('█'), Some(0.96));
        assert_eq!(t.coverage('╱'), Some(0.0));
        assert_eq!(t.coverage('x'), None);
        assert!(t.has_glyph('█') && t.has_glyph(' '));
        assert!(!t.has_glyph('╱') && !t.has_glyph('╲'), "missing = repertoire gap");
        assert!(!t.has_glyph('x'), "unlisted = not in repertoire");
        assert_eq!(t.missing(), &['╱', '╲']);
    }

    #[test]
    fn parse_rejects_structural_errors() {
        for (text, needle) in [
            ("name = \"x\"", "no [[glyphs]]"),
            ("[[glyphs]]\nch = \"a\"\ncoverage = 0.1", "no `name`"),
            ("name = \"x\"\n[[glyphs]]\nch = \"a\"", "no coverage"),
            ("name = \"x\"\n[[glyphs]]\nch = \"a\"\ncoverage = 1.5", "out of range"),
            ("name = \"x\"\n[[glyphs]]\nch = \"ab\"\ncoverage = 0.1", "single glyph"),
            (
                "name = \"x\"\n[[glyphs]]\nch = \"a\"\ncoverage = 0.1\n\n[[glyphs]]\nch = \"a\"\ncoverage = 0.2",
                "duplicate",
            ),
            ("name = \"x\"\nmissing = [\"a\"", "one-line array"),
            ("name = \"x\"\njunk", "key = value"),
        ] {
            let e = FontTable::parse(text).unwrap_err();
            assert!(e.contains(needle), "{text:?} → {e:?} (wanted {needle:?})");
        }
    }

    #[test]
    fn veto_downgrades_on_repertoire_gaps() {
        // Full coverage of every palette glyph → no veto at any tier.
        let full: String = table_for(&all_palette_glyphs(), &[]);
        let t = FontTable::parse(&full).unwrap();
        assert_eq!(t.veto_tier(GlyphTier::BrailleVerified), GlyphTier::BrailleVerified);
        assert_eq!(t.veto_tier(GlyphTier::UnicodeBlocks), GlyphTier::UnicodeBlocks);
        assert_eq!(t.veto_tier(GlyphTier::Ascii), GlyphTier::Ascii);

        // No braille → Braille request degrades to UnicodeBlocks.
        let braille: Vec<char> = all_palette_glyphs()
            .into_iter()
            .filter(|c| ('\u{2800}'..='\u{28FF}').contains(c))
            .collect();
        let t = FontTable::parse(&table_for(&all_palette_glyphs(), &braille)).unwrap();
        assert_eq!(t.veto_tier(GlyphTier::BrailleVerified), GlyphTier::UnicodeBlocks);
        assert_eq!(t.veto_tier(GlyphTier::UnicodeBlocks), GlyphTier::UnicodeBlocks);

        // No ╱ → any unicode request degrades to Ascii (missing box drawing).
        let t = FontTable::parse(&table_for(&all_palette_glyphs(), &['╱'])).unwrap();
        assert_eq!(t.veto_tier(GlyphTier::BrailleVerified), GlyphTier::Ascii);
        assert_eq!(t.veto_tier(GlyphTier::UnicodeBlocks), GlyphTier::Ascii);
        // Ascii is the floor, never vetoed — even by an absurd table.
        let t = FontTable::parse(&table_for(&[' ', 'x'], &[])).unwrap();
        assert_eq!(t.veto_tier(GlyphTier::Ascii), GlyphTier::Ascii);
    }

    /// The committed `fonts/*.toml` artifacts: every builtin parses, lists
    /// the full palette-glyph enumeration, and its repertoire produces the
    /// researched veto behavior (verified against each font's own cmap —
    /// see fonts/README.md): none of the four fonts carries the braille
    /// block (DejaVu's braille lives in DejaVu Sans, NOT the Mono face), so
    /// BrailleVerified always degrades; Liberation Mono lacks `╱╲` and the
    /// corner quadrants, Ubuntu Mono additionally lacks `‾` and every
    /// half/quadrant block — both degrade any unicode request to Ascii.
    #[test]
    fn builtins_load_and_veto_as_researched() {
        for &name in BUILTIN_FONT_TABLES {
            let t = FontTable::builtin(name).unwrap_or_else(|| panic!("{name} not builtin"));
            assert_eq!(t.name(), name);
            for ch in all_palette_glyphs() {
                assert!(t.coverage(ch).is_some(), "{name}: {ch:?} unlisted");
            }
            // Repertoire floor: ASCII is complete in every builtin.
            assert_eq!(t.veto_tier(GlyphTier::Ascii), GlyphTier::Ascii, "{name}");
            assert_ne!(
                t.veto_tier(GlyphTier::BrailleVerified),
                GlyphTier::BrailleVerified,
                "{name}: no common monospace font ships palette-7 braille"
            );
        }
        assert!(FontTable::builtin("comic-sans").is_none());
        let veto = |n: &str, want| FontTable::builtin(n).unwrap().veto_tier(want);
        use GlyphTier::{Ascii, UnicodeBlocks};
        assert_eq!(veto("dejavu-sans-mono", UnicodeBlocks), UnicodeBlocks);
        assert_eq!(veto("noto-sans-mono", UnicodeBlocks), UnicodeBlocks);
        assert_eq!(veto("liberation-mono", UnicodeBlocks), Ascii);
        assert_eq!(veto("ubuntu-mono", UnicodeBlocks), Ascii);
        // Conservative = ASCII repertoire only (the probe-default posture).
        assert_eq!(veto("conservative", UnicodeBlocks), Ascii);
    }

    /// Build a minimal table listing `glyphs` with `missing` gaps.
    fn table_for(glyphs: &[char], missing: &[char]) -> String {
        let esc = |c: char| match c {
            '"' => "\\\"".to_string(),
            '\\' => "\\\\".to_string(),
            c => c.to_string(),
        };
        let mut s = String::from("name = \"test\"\n");
        let miss: Vec<String> = missing.iter().map(|&c| format!("\"{}\"", esc(c))).collect();
        s.push_str(&format!("missing = [{}]\n", miss.join(", ")));
        for &ch in glyphs {
            let cov = if missing.contains(&ch) { 0.0 } else { 0.5 };
            s.push_str(&format!("[[glyphs]]\nch = \"{}\"\ncoverage = {cov:.6}\n", esc(ch)));
        }
        s
    }
}
