//! Glyph codecs — how a cell's features become a glyph and its colors.
//!
//! The asset stores features (luma taps, edge magnitude and orientation,
//! highlight/shadow flags, chroma), never glyphs. A **codec** is one complete
//! answer to "which glyph, in which colors, for these features":
//!
//! | codec | module | looks like |
//! |---|---|---|
//! | `pixels` | [`pixels`] | the three-layer compositor: tier ramps, half-blocks and quadrants on Unicode tiers — a low-res picture |
//! | `letters` | [`letters`] | printable characters ordered by ink on a dim tint of the cell's color (truecolor/256), directional ASCII strokes on edges, `█` for near-white cells and `▀`/`▄` for lit halves on block tiers |
//! | `ascii` | [`ascii`] | printable ASCII only on every tier, in bright per-glyph color on the terminal's own background — no blocks, no tint |
//!
//! Every codec reads the same [`CellInputs`] through the same NORM LUT and
//! the same [`PaletteSet`] (the palette selection still tells a codec which
//! repertoire the terminal can draw), writes the same [`CellState`] temporal
//! memory, and reports the same [`layer`](crate::layer) ids — so the
//! pipeline, the hysteresis resets, the layer mask and every overlay work
//! unchanged whichever one is active.
//!
//! # Adding a codec
//!
//! Write one module implementing [`GlyphCodec`] (`codec/<name>.rs`), then add
//! ONE line to the `registry!` list at the bottom of this file:
//! `Variant => module::Type`. That line declares the module and generates
//! the [`Codec`] variant, its place in [`Codec::ALL`] (the `/` cycle order),
//! its [`Codec::name`] arm and its [`compose_frame_codec`] dispatch arm.
//!
//! # Cost
//!
//! Dispatch is once per FRAME, not per cell: [`compose_frame_codec`] picks the
//! codec with one `match` and runs a per-cell loop monomorphized for it, so
//! choosing a codec adds no per-cell cost.

use crate::cell::Cell;
use crate::compose::{CellInputs, ComposeParams, FramePlanes, frame_impl};
use crate::grid::Grid;
use crate::hysteresis::{CellState, HysteresisState};
use crate::palette::PaletteSet;
use crate::viewport::Viewport;

/// One glyph codec: a pure per-cell mapping from features to a [`Cell`] plus
/// the winning [`layer`](crate::layer) id. See the module docs.
pub trait GlyphCodec {
    /// Registry name — what the `/` key shows, what `--codec` takes and what
    /// the per-video settings file stores. Lowercase ASCII, stable forever
    /// (saved files carry it).
    const NAME: &'static str;

    /// What the letterbox pads and a composition's gap frames hold.
    const PAD: Cell = Cell::BLANK;

    /// Compose one viewport cell. `lut` is the per-shot NORM LUT (shadow
    /// lift folded in), `set` the palette selection for this tier and
    /// density, `state` this cell's temporal memory. Must not allocate.
    fn cell(
        inp: &CellInputs,
        lut: &[u8; 256],
        set: &PaletteSet,
        params: &ComposeParams,
        state: &mut CellState,
    ) -> (Cell, u8);
}

macro_rules! registry {
    ($(#[$doc:meta])* $first:ident => $fmod:ident::$fty:ident,
     $($(#[$vdoc:meta])* $variant:ident => $module:ident::$ty:ident),* $(,)?) => {
        pub mod $fmod;
        $(pub mod $module;)*

        /// The codec registry: every glyph codec the player can switch to
        /// live. Generated by `registry!` — edit the list, not this enum.
        #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
        pub enum Codec {
            $(#[$doc])*
            #[default]
            $first,
            $($(#[$vdoc])* $variant,)*
        }

        impl Codec {
            /// Every registered codec in `/` cycle order (the default first).
            pub const ALL: [Codec; 1 $(+ registry!(@one $variant))*] =
                [Codec::$first, $(Codec::$variant),*];

            /// Registry name (see [`GlyphCodec::NAME`]).
            pub fn name(self) -> &'static str {
                match self {
                    Codec::$first => <$fmod::$fty as GlyphCodec>::NAME,
                    $(Codec::$variant => <$module::$ty as GlyphCodec>::NAME,)*
                }
            }

            /// Pad cell (see [`GlyphCodec::PAD`]).
            pub fn pad(self) -> Cell {
                match self {
                    Codec::$first => <$fmod::$fty as GlyphCodec>::PAD,
                    $(Codec::$variant => <$module::$ty as GlyphCodec>::PAD,)*
                }
            }
        }

        /// [`compose_frame`](crate::compose_frame) through `codec`, optionally
        /// recording the winning layer per cell into `mask` (as
        /// [`compose_frame_masked`](crate::compose_frame_masked)).
        /// `Codec::Pixels` is byte-identical to the plain entry points. Never
        /// allocates.
        ///
        /// # Panics
        /// As [`compose_frame_masked`](crate::compose_frame_masked).
        #[allow(clippy::too_many_arguments)]
        pub fn compose_frame_codec(
            codec: Codec,
            planes: &FramePlanes<'_>,
            vp: &Viewport,
            lut: &[u8; 256],
            set: &PaletteSet,
            params: &ComposeParams,
            state: &mut HysteresisState,
            out: &mut Grid<Cell>,
            mask: Option<&mut Grid<u8>>,
        ) {
            if let Some(m) = &mask {
                assert_eq!((m.cols(), m.rows()), (out.cols(), out.rows()), "layer mask != grid dims");
            }
            match codec {
                Codec::$first => {
                    frame_impl::<$fmod::$fty>(planes, vp, lut, set, params, state, out, mask)
                }
                $(Codec::$variant => {
                    frame_impl::<$module::$ty>(planes, vp, lut, set, params, state, out, mask)
                })*
            }
        }
    };
    (@one $x:ident) => { 1 };
}

registry! {
    Pixels => pixels::Pixels,
    Letters => letters::Letters,
    Ascii => ascii::Ascii,
}

impl Codec {
    /// Look a codec up by its registry name (exact, lowercase).
    pub fn from_name(name: &str) -> Option<Codec> {
        Codec::ALL.into_iter().find(|c| c.name() == name)
    }

    /// The next codec in [`Codec::ALL`], wrapping — one `/` press.
    pub fn next(self) -> Codec {
        let i = Codec::ALL.iter().position(|&c| c == self).unwrap_or(0);
        Codec::ALL[(i + 1) % Codec::ALL.len()]
    }

    /// Every registry name joined by `sep` — for help text and errors
    /// (`Codec::names(", ")`, `Codec::names("|")`).
    pub fn names(sep: &str) -> String {
        Codec::ALL.map(Codec::name).join(sep)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_is_complete_and_default_first() {
        assert_eq!(Codec::ALL[0], Codec::default(), "the default leads the cycle");
        for (i, a) in Codec::ALL.iter().enumerate() {
            assert!(Codec::ALL[i + 1..].iter().all(|b| b != a), "{a:?} listed twice");
        }
    }

    #[test]
    fn names_round_trip_and_are_unique() {
        for c in Codec::ALL {
            assert_eq!(Codec::from_name(c.name()), Some(c));
            assert!(c.name().bytes().all(|b| b.is_ascii_lowercase()), "{}", c.name());
        }
        assert_eq!(Codec::from_name("Pixels"), None, "names are exact");
        assert_eq!(Codec::from_name(""), None);
        assert_eq!(Codec::names(", "), "pixels, letters, ascii");
        assert_eq!(Codec::names("|"), "pixels|letters|ascii");
    }

    #[test]
    fn only_ascii_pads_on_the_terminal_background() {
        assert_eq!(Codec::Pixels.pad(), Cell::BLANK);
        assert_eq!(Codec::Letters.pad(), Cell::BLANK);
        let pad = Codec::Ascii.pad();
        assert_eq!((pad.glyph(), pad.bg, pad.attrs), (' ', crate::Rgb::BLACK, crate::cell::attrs::DEFAULT_BG));
    }

    #[test]
    fn next_cycles_through_all_and_wraps() {
        let mut c = Codec::default();
        let mut seen = Vec::new();
        for _ in 0..Codec::ALL.len() {
            seen.push(c);
            c = c.next();
        }
        assert_eq!(seen, Codec::ALL.to_vec(), "one press per codec, in registry order");
        assert_eq!(c, Codec::default(), "and back to the start");
        assert_eq!(Codec::ALL, [Codec::Pixels, Codec::Letters, Codec::Ascii]);
        assert_eq!(Codec::Pixels.next(), Codec::Letters);
        assert_eq!(Codec::Letters.next(), Codec::Ascii);
        assert_eq!(Codec::Ascii.next(), Codec::Pixels);
    }
}
